### ISSUE TITLE
treescan install question

### ISSUE THREAD

**Issue by LCHTTTT** [EasonXiao-888/GrootVL#4]
pip install -v -e .
Using pip 24.0 from /usr/local/miniconda3/envs/grootv/lib/python3.10/site-packages/pip (python 3.10)
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Obtaining file:///groot/GrootV/third-party/TreeScan
  Running command python setup.py egg_info
  /usr/local/miniconda3/envs/grootv/lib/python3.10/site-packages/torch/cuda/__init__.py:88: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525541990/work/c10/cuda/CUDAFunctions.cpp:109.)
    return torch._C._cuda_getDeviceCount() > 0
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/groot/GrootV/third-party/TreeScan/setup.py", line 72, in <module>
      ext_modules=get_extensions(),
    File "/groot/GrootV/third-party/TreeScan/setup.py", line 49, in get_extensions
      raise NotImplementedError("Cuda is not available.")
  NotImplementedError: Cuda is not available.
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/miniconda3/envs/grootv/bin/python -c '
  exec(compile('"'"''"'"''"'"'
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/groot/GrootV/third-party/TreeScan/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-jn02fx20
  cwd: /groot/GrootV/third-party/TreeScan/
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
这是什么问题呢

**Comment by EasonXiao-888** [comment]
it seems like you need to pip torch first

**Comment by StevenGrove** [comment]
You can try to reinstall the cuda library and set the "CUDA_HOME" environment properly.

**Comment by LCHTTTT** [comment]
> 看来你需要先点火炬

Thanks for the reply the issue has been resolved

**Comment by KyotoSakura** [comment]
> > 看来你需要先点火炬
> 
> Thanks for the reply the issue has been resolved

请问你是怎么解决的呢？

**Comment by KyotoSakura** [comment]
Hi,

I meet the same issue. Does your answer to @LCHTTTT means to install pytorch?

**Comment by Alan-Rr** [comment]
> Hi, 你好，
> 
> I meet the same issue. Does your answer to @LCHTTTT means to install pytorch?

Hi, I checked if pytorch was installed correctly first according to the GPT prompts, then set the CUDA header file path manually in the current terminal session and it installed correctly!

export CPLUS_INCLUDE_PATH=/usr/local/cuda/include:$CPLUS_INCLUDE_PATH

I hope that helps.

**Comment by KyotoSakura** [comment]
> > Hi, 
> > I meet the same issue. Does your answer to @LCHTTTT means to install pytorch?
> 
> Hi, I checked if pytorch was installed correctly first according to the GPT prompts, then set the CUDA header file path manually in the current terminal session and it installed correctly!
> 
> export CPLUS_INCLUDE_PATH=/usr/local/cuda/include:$CPLUS_INCLUDE_PATH
> 
> I hope that helps.

Thanks a lot.

**Comment by chengkai99** [comment]
请问版本是多少呢 cudatoolkit

**Comment by IceStreams** [comment]
> pip install -v -e . Using pip 24.0 from /usr/local/miniconda3/envs/grootv/lib/python3.10/site-packages/pip (python 3.10) Looking in indexes: https://mirrors.aliyun.com/pypi/simple Obtaining file:///groot/GrootV/third-party/TreeScan Running command python setup.py egg_info /usr/local/miniconda3/envs/grootv/lib/python3.10/site-packages/torch/cuda/**init**.py:88: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525541990/work/c10/cuda/CUDAFunctions.cpp:109.) return torch._C._cuda_getDeviceCount() > 0 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda' Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/groot/GrootV/third-party/TreeScan/setup.py", line 72, in ext_modules=get_extensions(), File "/groot/GrootV/third-party/TreeScan/setup.py", line 49, in get_extensions raise NotImplementedError("Cuda is not available.") NotImplementedError: Cuda is not available. error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. full command: /usr/local/miniconda3/envs/grootv/bin/python -c ' exec(compile('"'"''"'"''"'"' import os, sys, tokenize
> 
> try: import setuptools except ImportError as error: print( "ERROR: Can not execute since setuptools is not available in " "the build environment.", file=sys.stderr, ) sys.exit(1)`setup.py`
> 
> **file** = %r sys.argv[0] = **file**
> 
> if os.path.exists(**file**): filename = **file** with tokenize.open(**file**) as f: setup_py_code = f.read() else: filename = "" setup_py_code = "from setuptools import setup; setup()"
> 
> exec(compile(setup_py_code, filename, "exec")) '"'"''"'"''"'"' % ('"'"'/groot/GrootV/third-party/TreeScan/setup.py'"'"',), "", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-jn02fx20 cwd: /groot/GrootV/third-party/TreeScan/ Preparing metadata (setup.py) ... error error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details. 这是什么问题呢

请问你是怎么解决的呢，我是windows 10系统，也出现了类似的报错，如下：

Installing collected packages: tree_scan
  DEPRECATION: Legacy editable install of tree_scan==1.0 from file:///D:/2_Experiments/3_Change_Detection/51_GSTM_SCD_master/GrootV/third-party/TreeScan (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  Running setup.py develop for tree_scan
    Running command python setup.py develop
    running develop
    D:\1_Software_Installation\4_Anaconda\envs\py310\lib\site-packages\setuptools\command\develop.py:41: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************

    !!
      easy_install.initialize_options(self)
    D:\1_Software_Installation\4_Anaconda\envs\py310\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

    !!
      self.initialize_options()
    running egg_info
    writing tree_scan.egg-info\PKG-INFO
    writing dependency_links to tree_scan.egg-info\dependency_links.txt
    writing top-level names to tree_scan.egg-info\top_level.txt
    D:\1_Software_Installation\4_Anaconda\envs\py310\lib\site-packages\torch\utils\cpp_extension.py:497: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    reading manifest file 'tree_scan.egg-info\SOURCES.txt'
    writing manifest file 'tree_scan.egg-info\SOURCES.txt'
    running build_ext
    D:\1_Software_Installation\4_Anaconda\envs\py310\lib\site-packages\torch\utils\cpp_extension.py:382: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
      warnings.warn(f'Error checking compiler version for {compiler}: {error}')
    building 'tree_scan._C' extension
    D:\1_Software_Installation\4_Anaconda\envs\py310\lib\site-packages\torch\utils\cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
    If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
      warnings.warn(
    "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc" -c D:\2_Experiments\3_Change_Detection\51_GSTM_SCD_master\GrootV\third-party\TreeScan\tree_scan\csrc\bfs.cu -o build\temp.win-amd64-cpython-310\Release\2_Experiments\3_Change_Detection\51_GSTM_SCD_master\GrootV\third-party\TreeScan\tree_scan\csrc\bfs.obj -ID:\2_Experiments\3_Change_Detection\51_GSTM_SCD_master\GrootV\third-party\TreeScan\tree_scan\csrc -ID:\1_Software_Installation\4_Anaconda\envs\py310\lib\site-packages\torch\include -ID:\1_Software_Installation\4_Anaconda\envs\py310\lib\site-packages\torch\include\torch\csrc\api\include -ID:\1_Software_Installation\4_Anaconda\envs\py310\lib\site-packages\torch\include\TH -ID:\1_Software_Installation\4_Anaconda\envs\py310\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -ID:\1_Software_Installation\4_Anaconda\envs\py310\include -ID:\1_Software_Installation\4_Anaconda\envs\py310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++17 --use-local-env
    At end of source: error: expected a "}"
    D:\2_Experiments\3_Change_Detection\51_GSTM_SCD_master\GrootV\third-party\TreeScan\tree_scan\csrc\bfs.cu(113): note #3196-D: to match this "{"

    1 error detected in the compilation of "D:/2_Experiments/3_Change_Detection/51_GSTM_SCD_master/GrootV/third-party/TreeScan/tree_scan/csrc/bfs.cu".
    bfs.cu
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc' failed with exit code 1
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: 'D:\1_Software_Installation\4_Anaconda\envs\py310\python.exe' -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
    
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
    
    __file__ = %r
    sys.argv[0] = __file__
    
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
    
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'D:\\2_Experiments\\3_Change_Detection\\51_GSTM_SCD_master\\GrootV\\third-party\\TreeScan\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: D:\2_Experiments\3_Change_Detection\51_GSTM_SCD_master\GrootV\third-party\TreeScan\\
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
