### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by ShixuanGu** [EasonXiao-888/GrootVL#5]
Thanks for the great work! 

In cached_image_folder.py, a txt file (train.txt) is loaded, but imagenet doesn't have such files.

Could you kindly explain or share the file please :)

**Comment by EasonXiao-888** [comment]
@ShixuanGu  Thanks for your interest!
You can refer to this [data preparation](https://github.com/OpenGVLab/InternImage/tree/master/classification#data-preparation) and the [train.txt](https://drive.google.com/file/d/1mVfu9D9oQoRluqLWVf1_hhMtdXBGpQNm/view?usp=sharing) can be downloaded here. 
All the best!

**Comment by ShixuanGu** [comment]
thx!
