### ISSUE TITLE
question about flops

### ISSUE THREAD

**Issue by zhouyuan888888** [EasonXiao-888/GrootVL#7]
Hi, thank you for your great work and it is very interesting! But I have a question, how can I calculate the FLOPs of the whole model? Can you provide a script about calculating flops?

**Comment by EasonXiao-888** [comment]
Hi, @zhouyuan888888, thanks for your interest! we calculate the flops based on  for [InternImage_getflops_function](https://github.com/OpenGVLab/InternImage/blob/master/segmentation/get_flops.py#L50) with a replacement of our vision tree scanning algorithm in the manuscript. We are currently organizing the relevant code. If you have any questions, feel free to drop me.
