### ISSUE TITLE
Mamba 2 integration

### ISSUE THREAD

**Issue by looper99** [EasonXiao-888/GrootVL#8]
Hi, very nice work!

How hard is it to integrate Mamba 2 instead of Mamba 1 in this work?
What is the fastest way to do it and try?

Thanks.

**Comment by EasonXiao-888** [comment]
You can refer to mamba2 to modify our matrix A directly, but in the actual deployment stage, they use tensor core, while we are based on cuda core, so it needs to be further optimized.
