### ISSUE TITLE
Classification weights for small and base model cannot be accessed, only tiny!

### ISSUE THREAD

**Issue by looper99** [EasonXiao-888/GrootVL#9]
Hi, I just realized today that I can only access tiny pretrained model.

Please, can you make small and base weights also shareable to everyone without restrictions?

Thanks.

**Comment by EasonXiao-888** [comment]
Hi, @looper99 , the ckpt of small & base model can be accessed by the link provided in the readme. I'm not sure what's the problem, could you please provide more information, e.g. a screenshot, thanks!

**Comment by looper99** [comment]
Here it is:
![error](https://github.com/user-attachments/assets/73c087db-8ba5-467c-9b8c-b5fe0206c846)

Change Permissions for the File on Google Drive. The best way to test this is by opening these links in the private window; you will not be able to do it. You have access because you are the uploader.

Right-click on the file and select "Share."
Under Get Link, click "Restricted" (or the current setting) in the Share with People and Groups dialog. Change it to "Anyone with the link" to allow anyone with the Link to access the file. Set the permission level for the Viewer and click "Copy Link" to copy the Link with the updated permissions.

**Comment by EasonXiao-888** [comment]
@looper99 oops! sorry for my mistakes. I have adjusted the permissions you may check again. sorry again! Good Luck!❤️

**Comment by looper99** [comment]
@EasonXiao-888 Also, for the GrootL language model, it is restricted, if you can enable that also, thanks:
+GrootL	65.0	49.8	69.5	51.1	15.9	28.9	19.2	47.2	model

**Comment by EasonXiao-888** [comment]
@looper99 Already modified！

**Comment by looper99** [comment]
@EasonXiao-888, now everything works and thanks :heart: 

Congrats for the spotlight.
